### PR TITLE
fix docker build failed issue

### PR DESCRIPTION
**Pull request by jefby**
issue:

```
/usr/local/intel/mkldnn/include/mkldnn.hpp:192:62: error: exception handling disabled, use -fexceptions to enable
                 throw error(status, message, *error_primitive);
                                                              ^
In file included from ten
```

### CODE REVIEW

**Comment by YijinLiu** [comment]
Thanks for the PR. Somehow I didn't see it before I fixed it when I upgraded to 1.11.
It should build successfully now.

**Comment by jefby** [comment]
> Thanks for the PR. Somehow I didn't see it before I fixed it when I upgraded to 1.11.
> It should build successfully now.

ok
